<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?= $this->getLang() ?>" lang="<?= $this->getLang() ?>">
  <head>
    <?= $this->getChildHtml('head') ?>
  </head>
  <body<?= $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
    <?= $this->getChildHtml('after_body_start') ?>
    <div class="wrapper">
  	  <?= $this->getChildHtml('header') ?>
      <div class="main-left">
      	<div class="main-right">
      		<div class="main-top">
      			<div class="main-top-right"><?= $this->getLayout()->createBlock('cms/block')->setBlockId('telephone_info')->toHTML();?></div>
				<?php echo $this->getChildHtml('topMenu') ?>
				<div class="main-top-left"></div>
      		</div>
<div class="main-container col2-right-layout">
            <div class="main">
                <?php echo $this->getChildHtml('breadcrumbs') ?>
                <div class="col-main">
                    <?php echo $this->getChildHtml('global_messages') ?>
                    <?php echo $this->getChildHtml('content') ?>
                </div>
                <div class="col-right sidebar"><?php echo $this->getChildHtml('right') ?></div>
            </div>
        </div>
      		<div class="main-bottom">
      			
      			
      		</div>
      	</div>
      </div>
      <?= $this->getChildHtml('footer') ?>
      <?php echo $this->getChildHtml('before_body_end') ?>
     </div>
     <?php echo $this->getAbsoluteFooter() ?>
	</body>
</html>