<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?= $this->getLang() ?>" lang="<?= $this->getLang() ?>">
  <head>
    <?php echo $this->getChildHtml('head') ?>
  </head>
  <body>
  	<div class="main-container home-layout">
  	  <div class="header">
  	  	<img src="{{skin url='images/home/header-logo.png'}}" alt="*"/>
  	  </div>
      <div class="main-left">
      	<div class="main-right">
      		<div class="main-top"></div>
      		<div class="main-content">
      			<?php echo $this->getChildHtml('global_messages') ?>
            	<?php echo $this->getChildHtml('content') ?>
      		</div>
      		<div class="main-bottom"></div>
      	</div>
      </div>
      <div class="seo">SEO</div>
      <div class="footer">FOOTER</div>
	</body>
</html>