<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?= $this->getLang() ?>" lang="<?= $this->getLang() ?>">
  <head>
    <?= $this->getChildHtml('head') ?>
  </head>
  <body<?= $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
    <?= $this->getChildHtml('after_body_start') ?>
    <div class="wrapper">
  	  <?= $this->getChildHtml('header') ?>
      <div class="main-left">
      	<div class="main-right">
      		<div class="main-top">
      			<div class="main-top-left"></div>
      			<div class="main-top-right"></div>
      			MENU
      		</div>
      		<div class="main-content">
      		    <?= $this->getChildHtml('content') ?>
      		</div>
      		<div class="main-bottom">
      			<div class="main-bottom-right"></div>
      			 <?= $this->getLayout()->createBlock('cms/block')->setBlockId('brands')->toHTML();?>
      		</div>
      	</div>
      </div>
      <?= $this->getChildHtml('footer') ?>
     </div>
	</body>
</html>