<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?= $this->getLang() ?>" lang="<?= $this->getLang() ?>">
  <head>
    <?php echo $this->getChildHtml('head') ?>
  </head>
  <body<?= $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
    <?php echo $this->getChildHtml('after_body_start') ?>
    <div class="wrapper">
      <?php echo $this->getChildHtml('global_notices') ?>
      <div class="page">
      	<?php echo $this->getChildHtml('header') ?>
        <div class="main-container home-layout">
            <div class="main">
                <div class="col-wrapper">
                    <div class="col-main">
                        <?php echo $this->getChildHtml('global_messages') ?>
                        <?php echo $this->getChildHtml('content') ?>
                    </div>
                </div>
            </div>
            <div class="seo">
            	SEO
            </div>
        </div>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
  <?php echo $this->getAbsoluteFooter() ?>
  </body>
</html>