    <div class="nav-container">
        <h4 class="no-display"><?php echo $this->__('Category Navigation:') ?></h4>
        <ul id="anav">
            <li><a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>"><span>Home</span></a></li>
        <?php foreach ($this->getStoreCategories() as $_category): ?>
            <?php echo $this->drawItem($_category) ?>
        <?php endforeach ?>
        </ul>
    </div>
    <?php echo $this->getChildHtml('topLeftLinks') ?>