<div class="header-container">
    <div class="header">
    	<div class="header-right">
    		VOTRE BIJOUTIER....
    		<br>
    		<br>
    		<br>
    		<br>
    		Numéro local
    	</div>
    	LOGO
    </div>
</div>
TOP SEARCH
 <?php echo $this->getChildHtml('topSearch') ?>
 <p class="welcome-msg"><?php echo $this->getWelcome()?></p>
 TOPLINKS
<?php echo $this->getChildHtml('topLinks') ?>
STORE LANGUAGE
<?php echo $this->getChildHtml('store_language') ?>
TOP MENU
<?php echo $this->getChildHtml('topMenu') ?>
