<div class="header-container">
    <div class="header">
    	<?php if ($this->getIsHomePage()):?>
        <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
        <?php else:?>
        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
        <?php endif?>
    	<div class="header-right"><div>
			<?= $this->getLayout()->createBlock('cms/block')->setBlockId('header_right')->toHTML();?>
			ici
    	</div></div>
    	<?php echo $this->getChildHtml('store_language') ?>
    	<?php echo $this->getChildHtml('topContainer'); ?>
    	<p class="welcome-msg"><?php echo $this->getWelcome()?></p>
    </div>
</div>
