main_stone_type:
  entity_type_id: 4
  attribute_model:
  backend_model:
  backend_type: int
  backend_table:
  frontend_model:
  frontend_input: select
  frontend_label: Main Stone Type
  frontend_class:
  source_model: eav/entity_attribute_source_table
  is_required: 0
  is_user_defined: 1
  default_value: 
  is_unique: 0
  note: type de la pierre principale
  options:
    - Saphir/Diamant
    - Diamant
    - Emeraude/Diamant
  group: jewelry
  frontend_input_renderer:
  is_global: 1
  is_visible: 1
  is_searchable: 1
  is_filterable: 1
  is_comparable: 1
  is_visible_on_front: 1
  is_html_allowed_on_front: 1
  is_used_for_price_rules: 0
  is_filterable_in_search: 1
  used_in_product_listing: 0
  used_for_sort_by: 0
  is_configurable: 0
  apply_to:
  is_visible_in_advanced_search: 0
  position: 0
  is_wysiwyg_enabled: 1
  is_used_for_promo_rules: 0
  
  
main_stone_weight:
  entity_type_id: 4
  backend_type: varchar
  frontend_input: text
  frontend_label: Main Stone Weight
  is_required: 0
  is_user_defined: 1
  is_unique: 0
  note: poids de la pierre principale
  group: jewelry
  frontend_input_renderer:
  is_global: 1
  is_visible: 1
  is_searchable: 1
  is_filterable: 1
  is_comparable: 1
  is_visible_on_front: 1
  is_html_allowed_on_front: 1
  is_used_for_price_rules: 0
  is_filterable_in_search: 1
  used_in_product_listing: 0
  used_for_sort_by: 0
  is_configurable: 0
  apply_to:
  is_visible_in_advanced_search: 0
  position: 0
  is_wysiwyg_enabled: 1
  is_used_for_promo_rules: 0
  
main_stone_color:
  entity_type_id: 4
  backend_type: int
  frontend_input: select
  frontend_label: Main Stone Color
  source_model: eav/entity_attribute_source_table
  is_required: 0
  is_user_defined: 1
  default_value: 
  is_unique: 0
  note: couleur de la pierre principale
  options:
    - H
    - G
    - H/G
  group: jewelry
  frontend_input_renderer:
  is_global: 1
  is_visible: 1
  is_searchable: 1
  is_filterable: 1
  is_comparable: 1
  is_visible_on_front: 1
  is_html_allowed_on_front: 1
  is_used_for_price_rules: 0
  is_filterable_in_search: 1
  used_in_product_listing: 0
  used_for_sort_by: 0
  is_configurable: 0
  apply_to:
  is_visible_in_advanced_search: 0
  position: 0
  is_wysiwyg_enabled: 1
  is_used_for_promo_rules: 0
  
main_stone_purete:
  entity_type_id: 4
  backend_type: int
  frontend_input: select
  frontend_label: Main Stone purete
  source_model: eav/entity_attribute_source_table
  is_required: 0
  is_user_defined: 1
  default_value: 
  is_unique: 0
  note: pureté de la pierre principale
  options:
    - SI
    - VS
    - VS1
  group: jewelry
  frontend_input_renderer:
  is_global: 1
  is_visible: 1
  is_searchable: 1
  is_filterable: 1
  is_comparable: 1
  is_visible_on_front: 1
  is_html_allowed_on_front: 1
  is_used_for_price_rules: 0
  is_filterable_in_search: 1
  used_in_product_listing: 0
  used_for_sort_by: 0
  is_configurable: 0
  apply_to:
  is_visible_in_advanced_search: 0
  position: 0
  is_wysiwyg_enabled: 1
  is_used_for_promo_rules: 0