main_stone_type:
  entity_type_id: 4
  attribute_model:
  backend_model:
  backend_type: int
  backend_table:
  frontend_model:
  frontend_input: select
  frontend_label: Main Stone Type
  frontend_class:
  source_model: eav/entity_attribute_source_table
  is_required: 0
  is_user_defined: 1
  default_value: 
  is_unique: 0
  note: type de la pierre principale
  options:
    - Saphir/Diamant
    - Diamant
    - Emeraude/Diamant
  group: jewelry
  frontend_input_renderer:
  is_global:
  is_visible:
  is_searchable:
  is_filterable:
  is_comparable:
  is_visible_on_front:
  is_html_allowed_on_front:
  is_used_for_price_rules:
  is_filterable_in_search:
  used_in_product_listing:
  used_for_sort_by:
  is_configurable:
  apply_to:
  is_visible_in_advanced_search:
  position:
  is_wysiwyg_enabled:
  is_used_for_promo_rules:
  
  
main_stone_weight:
  entity_type_id: 4
  backend_type: varchar
  frontend_input: text
  frontend_label: Main Stone Weight
  is_required: 0
  is_user_defined: 1
  is_unique: 0
  note: poids de la pierre principale
  group: jewelry
  
main_stone_color:
  entity_type_id: 4
  backend_type: int
  frontend_input: select
  frontend_label: Main Stone Color
  source_model: eav/entity_attribute_source_table
  is_required: 0
  is_user_defined: 1
  default_value: 
  is_unique: 0
  note: couleur de la pierre principale
  options:
    - H
    - G
    - H/G
  group: jewelry
  
main_stone_purete:
  entity_type_id: 4
  backend_type: int
  frontend_input: select
  frontend_label: Main Stone purete
  source_model: eav/entity_attribute_source_table
  is_required: 0
  is_user_defined: 1
  default_value: 
  is_unique: 0
  note: pureté de la pierre principale
  options:
    - SI
    - VS
    - VS1
  group: jewelry