<?php 

$_productCollection=$this->getLoadedProductCollection();

$number_of_products = $this->getNumProducts(); 
Mage::log($number_of_products);

?>
<?php 
if($_productCollection->count()): ?>
<div class="block block-popular">
        <div class="block-title">
        <strong><span><?php echo $this->__('Most Popular')?></span></strong>
    </div>
    <div class="block-content">
                
<?php $_iterator = 0;
$i = 0; ?>
        <ol class="mini-products-list" id="block-popular">
        <?php foreach($_productCollection as $_item): ?>
        <?php if ($i++ >= $number_of_products) break; ?>
            <li class="item">
                <div class="product">
                    <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(100) ?>" width="100" height="100" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
                    <div class="product-details">
                        <p class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></p>
                        <?php echo $this->getPriceHtml($_item, true, '-related') ?>
                        <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-info"><?php echo $this->__('info')?></a>
                    </div>
                </div>
            </li>
        <?php endforeach ?>
        </ol>
</div>
</div>
<?php endif; ?>